# Generated by Django 5.2.8 on 2025-11-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_registration_events_regi_event_i_c98244_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentactivity',
            name='action',
            field=models.CharField(choices=[('registered', 'Registered'), ('cancelled', 'Cancelled'), ('waitlisted', 'Joined Waitlist'), ('promoted', 'Promoted from Waitlist')], max_length=20),
        ),
    ]
